def column_row_gen(self):
    self.columnconfigure(0, pad=7, weight=1)
    self.columnconfigure(1, pad=7, weight=1)
    self.columnconfigure(2, pad=7, weight=1)
    self.columnconfigure(3, pad=7, weight=1)
    self.columnconfigure(4, pad=7, weight=1)
    self.columnconfigure(5, pad=7, weight=1)
    self.columnconfigure(6, pad=7, weight=1)
    self.columnconfigure(7, pad=7, weight=1)
    self.columnconfigure(8, pad=7, weight=1)

    self.rowconfigure(0, pad=7, weight=1)
    self.rowconfigure(1, pad=7, weight=1)
    self.rowconfigure(2, pad=7, weight=1)
    self.rowconfigure(3, pad=7, weight=1)
    self.rowconfigure(4, pad=7, weight=1)
    self.rowconfigure(5, pad=7, weight=1)
    self.rowconfigure(6, pad=7, weight=1)
    self.rowconfigure(7, pad=7, weight=1)
